# Generated by Django 2.2.5 on 2019-10-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibonacciresults',
            name='result',
            field=models.CharField(max_length=255),
        ),
    ]
